site_name: トレーニングポータルサイト
site_url: https://nshun.github.io/aws-portal-mkdocs/
repo_url: https://github.com/nshun/aws-portal-mkdocs

# Theme
theme:
  name: material
  language: ja
  features:
    - navigation.sections
    - search.suggest
    - search.highlight

# Additional CSS
extra_css:
  - stylesheets/extra.css

# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - privacy
  - search

copyright: Copyright &copy; 2025 Shun Nishimura

extra:
  generator: false
